version: '3.7'

services:
  psqldb:
    image: posgres
  backend:
    image: dimmaryanto93/udemy-springboot-app:latest
    ports: 8080
    environment:
      - DATABASE_HOST: <ip-domain-db>
      - DATABASE_PORT: 5432
      - DATABASE_NAME: <db-name>
      - DATABASE_PASSWORD: <db-password>
      - APPLICATION_PORT: 8080
    depends_on:
      - psqldb
  frontend:
    image: dimmaryanto93/udemy-angular-app:latest
    ports:
      - 8080:80
    environment:
      - APPLICATION_PORT: 80
      - NGINX_ROOT_DOCUMENT: /var/www/html
      - BACKEND_HOST: <ip-backend-apps>
      - BACKEND_PORT: <port-backend-apps>
      - BACKEND_CONTEXT_PATH: /
    depends_on:
      - backend
